name = "DDG"
uuid = "0d8945ae-3c78-4d89-9fb2-eb311a132810"
repo = "https://github.com/jakeoung/DDG.jl"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
